title: Site

pages: default

fields:
  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text

  description:
    label: Description
    type:  textarea

  footer:
    label: Footer Text
    type:  textarea

  copyright:
    label: Copyright
    type:  textarea

  navigationtype:
    label: Navigation Type
    type: radio
    default: navoffcanvas
    options:
      navoffcanvas: Off-Canvas
      navstandard: Standard
